/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../src/client/routes/__root'
import { Route as KontolRouteImport } from './../src/client/routes/kontol'
import { Route as IndexRouteImport } from './../src/client/routes/index'

const KontolRoute = KontolRouteImport.update({
  id: '/kontol',
  path: '/kontol',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontol': typeof KontolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontol': typeof KontolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontol': typeof KontolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontol'
  id: '__root__' | '/' | '/kontol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontolRoute: typeof KontolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kontol': {
      id: '/kontol'
      path: '/kontol'
      fullPath: '/kontol'
      preLoaderRoute: typeof KontolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontolRoute: KontolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
